### ISSUE TITLE
HTTPS Mixed Content

### ISSUE THREAD

**Issue by ZebraNorth** [Csardelacal/YCH-Issues#17]
Visiting an auction page with HTTPS gives mixed content warnings

The offending requests are:
`<img src="http://account.commishes.com/image/user/2059/64" class="user-icon small" title="Icons handled by gravatar">`
`var crons = ['/cron/', 'http://account.commishes.com//cron'];`

**Comment by Csardelacal** [comment]
Hey there MrZebra! Thanks for the report, I will look into those. Shouldn't be a complicated fix!

**Comment by Csardelacal** [comment]
Once the new version of the authentication service is online this should be completely fixed.
Thanks again for the report!
