### ISSUE TITLE
 No bid is displayed

### ISSUE THREAD

**Issue by DecembristFlower** [Csardelacal/YCH-Issues#20]
Hello
 Platform: desktop
 Operating system:  Windows
 Browser:  Chrome
https://ych.commishes.com/auction/show/36KC/night-tear/ - auction
https://ych.commishes.com/bids/manage/105100/ - bidlist
I added new auction. Then, I got start bid, by saw it in bidlist. Over time I got new bid, which was just second start bid. I went into auction and I saw, that there no bid.
I tryied to 
1) refresh the page
2) Relogin
3) remove second bid >[u can see it there ](https://sta.sh/0kjuwsz7neb)
P.s. I didnt get ani notification

**Comment by Csardelacal** [comment]
Hello Decembrist! Thanks for the report! 

It seems both the bids you have received have yet to be confirmed. The buyers have been sent an email with instructions on how to confirm the bid (it's just clicking a link on the email) but have not yet done so.

The system prevents spam by not accepting any bids from any user until it has been able to verify that the user is not just a random spammer. 

I do wish you the best of luck and hope the users will find the email and verify their bid.

**Comment by Csardelacal** [comment]
Just as a follow up. I added a brief page to our wiki explaining what guest bidding does (https://wiki.commishes.com/index.php?title=Bidding_as_a_guest). I hope it'll be useful in the future for users having this issue.

Thanks again for the report!
