### ISSUE TITLE
Got both winning and losing emails after winning an auction.

### ISSUE THREAD

**Issue by MDGLee** [Csardelacal/YCH-Issues#24]
Platform: Desktop
 Operating system: Windows 10 Pro, Build 17134.407
 Browser: Google Chrome
 URL: https://ych.commishes.com/auction/show/43AR/spitfire-by-hampony/
 
What were you trying to do: Placed a $20 bid on this item with about 7-10 minutes left in the auction, outbidding a $15 bid. Sniping protection was not enabled. No one else bidded.

 What was supposed to happen: At the end of the auction, I would have received the two emails saying "You won the auction" and "[CRM] Your commission was created."
 
What happened: I got those two emails, but got a third email saying "You lost bidding on [item name by artist]!" Going to the original auction page, my bid was no longer visible. The original CRM still existed and I was able to arrange for payment and shipping with the seller, so the winner's identity is not the issue, only the glitch.

![2018 11 29 03 15](https://user-images.githubusercontent.com/45453930/49215191-7a214200-f385-11e8-923f-4145fbd04548.PNG)

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T94](https://phabricator.magic3w.com/T94)

-The Commishes Team
