### ISSUE TITLE
Inaccurate Auction Timers

### ISSUE THREAD

**Issue by MarshmallowTaffy** [Csardelacal/YCH-Issues#25]
- Platform: Laptop
- Operating system: Windows 10 home
- Browser: Chrome + Brave
- URL: no specific auction; observed more than once
 
- What were you trying to do:
 Trying to snipe, err I mean _bid_ in an auction, the timer would display roughly :20 seconds or more remaining but when bid info is entered the button would be non responsive until the time ebbed away. First time observed without an account; made an account specifically to try and avoid it and then encountered it again even on a different browser,

- What was supposed to happen:
Bid should have cleared one would think, unless another user bid the same / higher amount at the same time or seconds before hitting the button. This was not true in either case according to the bid history on display.
 
- What happened:
Button for "Place Bid" is unresponsive until displayed (inaccurate) time finishes. Sadness ensues.

**NOTE**: May be related to Issue #13 but to my knowledge my system clock is synchronized. I could be wrong or YCH could have a _slightly_ different (15 seconds!) server time. Though error is likely with my end, 2 friends have related the same issue to me though they simply accept it.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T93](https://phabricator.magic3w.com/T93)

-The Commishes Team
