### ISSUE TITLE
Unable to bid. bid is not displayed

### ISSUE THREAD

**Issue by dragonoidsix** [Csardelacal/YCH-Issues#26]
Platform: desktop
Operating system: Windows 10
Browser: Microsoft Edge
-----
Platform: iPhone 8
Operating system: Apple
Browser: Safari

Account name: Dragonoidsix

My account will not let me bid for some weird reason. I even made sure to switch platform to ensure it was not a device issue. I place a bid and it isn't showing even though I have my bids auto verified. And in order to place a bid and for it to appear, I have to log out of my account and Guest bid it. 
I tried to bid several time on a few different auctions and regardless of which one it was, If I was logged in, my bid wouldn't appear. I'm attaching images for evidence of bid placed that do not appear. Please note the time above the bid. 

Any assistance would be appreciated. Please excuse any terrible spelling. 
![screenshot 59](https://user-images.githubusercontent.com/46273790/50554530-b6480b00-0c81-11e9-9ccc-f2a356bd476c.png)
![screenshot 58](https://user-images.githubusercontent.com/46273790/50554531-b6480b00-0c81-11e9-9fa0-45fc3271f049.png)
![screenshot 57](https://user-images.githubusercontent.com/46273790/50554532-b6e0a180-0c81-11e9-9870-e6087499ca4b.png)
![screenshot 56](https://user-images.githubusercontent.com/46273790/50554533-b6e0a180-0c81-11e9-9d0b-cf4a8187f085.png)

**Comment by Narikusha** [comment]
I have exactly the same problem! qwq

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T92](https://phabricator.magic3w.com/T92)

-The Commishes Team
