### ISSUE TITLE
"Watch" button on Desktop lacks color

### ISSUE THREAD

**Issue by TakaNeko13** [Csardelacal/YCH-Issues#28]
Platform: Desktop
 Operating system: Windows
 Browser: Chrome
 URL:  https://ych.commishes.com/auction/show/5DM1/so-cold/
 
 What were you trying to do:
Select the "Watch"  button with the little heart next to it.
 
 What was supposed to happen:
On the mobile version of YCH.Commishes, touching the "Watch" button turns the text noticeably green and the little heart turns red. This is a clear indicator to me that I'm watching the item and it will appear in my Watchlist.

 What happened:
On the Desktop version of YCH.Commishes, clicking the "Watch" button does not change the color of the letters or the heart. If there is a change, it is very very hard to see. At that point, I can't tell if I am watching the auction or not. I think there is a particular bug that is not highlighting the "Watch" button when clicked.

If you could look into it, I would really appreciate it. Thank you.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T91](https://phabricator.magic3w.com/T91)

-The Commishes Team
