### ISSUE TITLE
NSFW thumbnails show on individual auction pages when not logged in.

### ISSUE THREAD

**Issue by GalacticScarab** [Csardelacal/YCH-Issues#29]
Platform: desktop
 Operating system: Any
 Browser: Any
 URL: 
 
 **What were you trying to do:**
N/A
 
 **What was supposed to happen:**
NSFW "Samples" images on auction pages should be hidden or censored to users who are not logged in.
 
 **What happened:**
On the individual auction pages NSFW "Samples" images show without being logged in, even on SFW auctions.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T90](https://phabricator.magic3w.com/T90)

-The Commishes Team
