### ISSUE TITLE
Commission disappeared 

### ISSUE THREAD

**Issue by fenithatsleeps** [Csardelacal/YCH-Issues#30]
Platform: [desktop|mobile]
 Operating system: [Android, Windows]
 Browser: [Chrome]
 
 What were you trying to do: going to opened commisions from my profile on ych.commishes
 
 What was supposed to happen: showed my commissions as an artist on crm.commission 
 
 What happened: no commisions founded. Nor opened neither closed

**Comment by fenithatsleeps** [comment]
![IMG_20190313_105216](https://user-images.githubusercontent.com/48509361/54262059-5a9dd600-457e-11e9-9149-f0ba6d908a9c.jpg)
![IMG_20190313_105241](https://user-images.githubusercontent.com/48509361/54262061-5b366c80-457e-11e9-9410-4be77d9c1bfc.jpg)
![IMG_20190313_105255](https://user-images.githubusercontent.com/48509361/54262063-5b366c80-457e-11e9-95b3-fc7752b36f74.jpg)

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T87](https://phabricator.magic3w.com/T87)

-The Commishes Team
