### ISSUE TITLE
SQL error gives major database record leak

### ISSUE THREAD

**Issue by ThomasvanderSchaft** [Csardelacal/YCH-Issues#31]
Platform: mobile
Operating system: Android
Browser: Chrome

What were you trying to do: Normal browsing. Error shows up on page when certain conditions are met.
What was supposed to happen: try catching error. Perhaps formatting it to a bug alert directed to the developers

What happened: error shows up and when pressed it exposes very sensitive database record names. Which are available to everyone.

Apologies for being cryptic. One programmer to another, I don't think you would want me to show screenshots of evidence or steps on how to get there since it is very sensitive data. I can show how I got to the error and what it is displaying, but I would also rather do that in a direct message on platforms like Discord. I'll be able to provide all needed information to your developers without potential hackers to lurk over it.

**Comment by Csardelacal** [comment]
Hello Cyberhide! I sent you a message on Discord. Thanks for reaching out! - C#
