### ISSUE TITLE
Error with Paypal

### ISSUE THREAD

**Issue by mosasakkine** [Csardelacal/YCH-Issues#32]
I selected to promote my auction, got taken to paypal to pay, then after submitting payment, received an error. My auction didn't get posted, and money was still taken from my paypal account. Please advise.

Edit: False alarm, sorry. When I checked my "auctions" list, it said I had none, so I thought it didn't get submitted. Apparently the site logged me out when it errored. Logged back in, everything is there, finished submitting my auction and everything seems fine.

**Comment by Csardelacal** [comment]
Great to hear it worked out for you. Just in case this should ever happen to you again, and for future reference. Payment issues are best discussed by sending us an email, or contacting us privately.

Infos are posted here: https://ych.commishes.com/home/help
