### ISSUE TITLE
CRM. Content loading with ajax does not render marked text properly

### ISSUE THREAD

**Issue by nokitakaze** [Csardelacal/YCH-Issues#34]
1. I open some long conversation `https://crm.commishes.com/task/show/12345/`
2. I see only N recent messages, they contain proper hypertext link `<a href=...`
3. I scroll up to the top, and JS script starts to load old messages with ajax using url `https://crm.commishes.com/task/show/12345.json?s=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX&before=987654`
4. `.messages[0].body` contain only raw non processed text. So I see text `https://example.com` as a text, but not as a link `<a href="https://example.com">...`

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T85](https://phabricator.magic3w.com/T85)

-The Commishes Team
