### ISSUE TITLE
Porfolio. Can't see all artist's works

### ISSUE THREAD

**Issue by nokitakaze** [Csardelacal/YCH-Issues#35]
I can't see where should I put Portfolio's bugs https://wiki.commishes.com/index.php?title=Reporting_Bugs , so I will create it here. Sorry.

All of these links are **not safe for work**.

1. I open random artists. For example https://portfolio.commishes.com/user/Sich_Laity/ 
2. Site says me he has 57 works.
3. I count all works I see, but it seems there are only 36 items.
4. I open next https://portfolio.commishes.com/user/Simargl/ , site says me it is 30 works, but I could see only 19

Some tests:
- https://portfolio.commishes.com/user/Sich_Laity/ 36 of 57
- https://portfolio.commishes.com/user/Simargl/ 19 of 30
- https://portfolio.commishes.com/user/Messenger/ **6 of 78**
- https://portfolio.commishes.com/user/tabu-rat/ 39 of 45

Okay, let's just say an artist hide their works, but then I open https://portfolio.commishes.com/upload/show/3OJ4/ and see 6 works in related block and some of them don't exist in https://portfolio.commishes.com/user/Messenger/ . I could even open https://portfolio.commishes.com/upload/show/3OJ5/ , which didn't appear in portfolio page and see other 6 works in related!

So there is one of two possible bugs:
1. An artist hide their works, but they still appear in related art and on the counter on main artist's page
2. There is some bug with `https://portfolio.commishes.com/user/XXXXXXXXXXX.json` , and it does not show me all works

And sometimes it works perfectly:
- https://portfolio.commishes.com/user/hikkara/ All 98 items

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T83](https://phabricator.magic3w.com/T83)

-The Commishes Team
