### ISSUE TITLE
CRM. Page titles don't look usable

### ISSUE THREAD

**Issue by nokitakaze** [Csardelacal/YCH-Issues#36]
This is how the CRM looks like with many opened pages:
![Снимок](https://user-images.githubusercontent.com/9131758/60918749-b8c49680-a29c-11e9-9119-8120c25f85c5.PNG)

This is how Wikipedia looks like in such situation
![2](https://user-images.githubusercontent.com/9131758/60919369-35a44000-a29e-11e9-8d05-b82401250cbf.PNG)

All auctions have their own name https://ych.commishes.com/auction/show/7GKA/life-size-pony-plush/ ("LIFE SIZE PONY PLUSH!"), and we could read it in title of tab when an auction is going. So I think the CRM could use that title as a title for "task" page. Do you copy this information, don't you? 
I prefer titles like `Auction title [artist username] — CRM Commishes` for a client, and `Auction title [commissioner username] — CRM Commishes` for an artist. If a task doesn't have it own title (maybe it's a commission made with commission button) you could use just `artist username — CRM Commishes`.

The same goes for https://crm.commishes.com/account/
All I see it's my username, label "in progress" and last message in thread. I don't know which auction it is, when was that last message, who was the creator of this message (me or an artist) and who is an artist.

**It is very unhandy.**

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T84](https://phabricator.magic3w.com/T84)

-The Commishes Team
