### ISSUE TITLE
Can't promote an auction

### ISSUE THREAD

**Issue by Dalevski** [Csardelacal/YCH-Issues#37]
This is it
![image](https://user-images.githubusercontent.com/54702028/64000140-c57fa100-cb0d-11e9-9804-cd6a0bc4a7a9.png)
I don't get it. My paypal is okay, I checked it, I have enough money on my card to pay the price... What happened?

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T82](https://phabricator.magic3w.com/T82)

-The Commishes Team

**Comment by ghost** [comment]
I paid and promoted my auction but it doesn’t appear on the featured
![Screenshot_2](https://user-images.githubusercontent.com/64157765/80012247-af2bb880-84d5-11ea-8be8-d82f4a9bad11.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/64157765/80012332-d71b1c00-84d5-11ea-8954-9a7c10ce92d7.jpg)
