### ISSUE TITLE
Auction page sometimes breaks after the auction is over

### ISSUE THREAD

**Issue by kksmith82** [Csardelacal/YCH-Issues#39]
Platform: mobile
 Operating system: Android
 Browser: Chrome
 URL: https://ych.commishes.com/auction/show/9L26/halloween-ych/
https://ych.commishes.com/auction/show/9IEK/-queen--any-race/
https://ych.commishes.com/auction/show/9I89/commission-slot-watercolor/

 What were you trying to do: Visit the auction page for a finished auction (doesn't seem to matter if I won or even bid on it).  This only seems to happen sometimes (I included a few links I noticed it with) 
 
 What was supposed to happen: Take me to the auction page
 
 What happened: I get a 404 error page.  The pages still show in my watchlist and for the ones I won, I can see the original listing text in CRM, but the actual page doesn't work.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T81](https://phabricator.magic3w.com/T81)

-The Commishes Team
