### ISSUE TITLE
Explicit thumbnails nicer to look at

### ISSUE THREAD

**Issue by RalekArts** [Csardelacal/YCH-Issues#4]
Remove placeholder from Explicit thumbnails and replace with brighter warning sign, [see:Derpibooru for example](http://i.imgur.com/MXwUnx2.png).
For slower end users, possibly also add a text warning in the form of a red E to the left of the title. Simple, but lets users who's images haven't loaded yet from clicking on one accidentally.
![](http://i.imgur.com/LXB7Pfa.png)

**Comment by Csardelacal** [comment]
I added the red (E) to the explicit auctions. Also rearranged the layout of the title a little so the card doesn't look so crammed.

Also, would need a suggestion for that explicit image.
