### ISSUE TITLE
Error on CRM page for won auction

### ISSUE THREAD

**Issue by kksmith82** [Csardelacal/YCH-Issues#40]
Platform: mobile
Operating system: Android
Browser: Chrome
URL: https://crm.commishes.com/task/show/189356/?s=OJedKO5evYRM6606eCqCdxo5ephPiJNyV3mJNK7aubcJpIShgu

What were you trying to do: Visit the CRM page for the auction I won

What was supposed to happen: The page does not throw an error 

What happened: I get the following error on every CRM page:
![Screenshot_20191017-211556](https://user-images.githubusercontent.com/56706732/67060763-b5ef0280-f123-11e9-8230-5f3eeb05c5bc.png)

It looks like this error goes away after the ych is marked completed by the artist.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T80](https://phabricator.magic3w.com/T80)

-The Commishes Team
