### ISSUE TITLE
Gesture Request: Add winning bid price to CRM page

### ISSUE THREAD

**Issue by kksmith82** [Csardelacal/YCH-Issues#41]
I would like to suggest the winning bid price be added to the CRM page somewhere.  I've won a few auctions and it's sometimes hard to keep track of how much I paid for each one by the time the artist gives me the PayPal information to pay.  I've been keeping them on my watchlist as a workaround but it'd be nice if the CRM page listed this price so I can make sure the artist is paid the correct amount :)

**Comment by kksmith82** [comment]
Sorry, the title is supposed to read "Feature Request" - stupid phone autocorrect

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T88](https://phabricator.magic3w.com/T88)

-The Commishes Team
