### ISSUE TITLE
Finished auction artwork dowloaded at portfolio page, but not at auction

### ISSUE THREAD

**Issue by Estih** [Csardelacal/YCH-Issues#44]
Hello and thank you for your work! 
I've noticed that my finished artwork for my customer was uploaded to my portfolio page, but not to the auction page. Will it always works like this now, or is it a mistake? I noticed it at other guys' pages too.

**Comment by Sakuro24** [comment]
I have the same problem! :/

**Comment by Csardelacal** [comment]
Hey there @Estih,

this is a normal process. We're removing the old "Finished auctions" section to be able to roll out newer and more interesting updates. Old auctions are being transferred to your Portfolio right now, new uploads will automatically be sent to Portfolio.

During this process the system will also start removing the old stars that appeared next to your username and replace them (if applicable) with green circles.
