### ISSUE TITLE
Error uploading bid result

### ISSUE THREAD

**Issue by RagnaDrasil** [Csardelacal/YCH-Issues#45]
**Platform:** **desktop**
 **Operating system:** **Windows**
 **Browser:** **Chrome**
 **URL:** https://portfolio.commishes.com/upload/show/683Q
 
 **What were you trying to do:** 
Once I finished the artwork, I was going to upload it. Previously changed in the bid to questionable in case it was sensitive content and once I uploaded the drawing it did not appear in my ''auction page'', it appeared in ''portfolio''

I checked the finished page also to see if it was there but there was no sign of the drawing whatsoever. 
Because I already did the ''upload result'' I don't have the option anymore even after deleting the image.
 
 **What was supposed to happen:** Drawing (bid result) appear in auction page and not portfolio.
 
 **What happened:** Drawing appeared in portfolio instead of the auction page.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T89](https://phabricator.magic3w.com/T89)

-The Commishes Team
