### ISSUE TITLE
Auction result uploaded improperly?

### ISSUE THREAD

**Issue by breioom** [Csardelacal/YCH-Issues#46]
So, I got an email to follow up an auction and so I followed it, logged in, and uploaded a YCH result. However, it gave me a 500 error.

Now, when I view my auctions within "https://ych.commishes.com/account/", there is no option to upload the result. It must have uploaded. However, when I click the auction, and click "here" in "This auction ended already. Check out how it turned out here" I get another 500 error.

![aaa](https://user-images.githubusercontent.com/61770880/75845841-59c20d80-5da8-11ea-98df-dd24f2fc6443.png)

I'm now worried that this will affect my reputation on the site, if others cannot see the result. What can be done to remedy the situation?

**Comment by breioom** [comment]
Can't believe nobody has even looked at this. Little lazy, guys.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T79](https://phabricator.magic3w.com/T79)

-The Commishes Team
