### ISSUE TITLE
Can't create commission (CRM)

### ISSUE THREAD

**Issue by crosstheswirl** [Csardelacal/YCH-Issues#47]
Everytime I Try to open one of my auctions to be on CRM, it gives me a error. I linked the screenshots.

https://sta.sh/2k1m2lz2o93?edit=1

I also can't see any image that is a GIF. Just shows up as a tiny box.
AND I  can't upload results. It goes through but when I go to look to see if it REALLY uploaded. It's blank and it did not upload at all.
I did not change the way I draw or my files. Nothing changed and these bugs are happening.

This has been happening for a while and it's not going away, only getting worse.

**Comment by kacecfox** [comment]
Thank you for your help to make Commishes even better.
This ticket has been reviewed and moved to our issue tracking system.

[https://phabricator.magic3w.com/T127](https://phabricator.magic3w.com/T127)

-The Commishes Team
