### ISSUE TITLE
Buyout price [Auto-buy]

### ISSUE THREAD

**Issue by RalekArts** [Csardelacal/YCH-Issues#5]
Allows artists when designing their auction to set a buyout price. At any point in time during the auction a user may commit to pay the buyout price, and the auction will end and Artist notified.

Other features:
- Instead of ending auction, place bids and countdown on hold until artist accepts or rejects offer on grounds of feeling illegitimately bought, or fake. 
- Can be integrated with a wallet system to only allow artist to confirm or deny when the user is non-registered and does not have the funds available In their wallet. Users who have the funds in their wallet will automatically be accepted and funds deducted.
- Display autobuy price next to or below current bid on home page.

**Comment by Csardelacal** [comment]
This is implemented already. Forgot to close the ticket.
