### ISSUE TITLE
Anchor gets split off of URL

### ISSUE THREAD

**Issue by StellaeAlis** [Csardelacal/YCH-Issues#57]
## System information
Platform: Desktop
Operating system: Windows
Browser: Firefox
 
## What were you trying to do
Trying to send an artist my reference sheet.
 
## What was supposed to happen
The link was supposed to be fully shown and clickable.
 
## What happened
The anchor part of the URL was sent as normal text, and the link was no longer correct.

## Example
The link "https://toyhou.se/2471965.kiana/gallery#8622700" did get send as "[toyhou.se/24719...na/gallery](https://toyhou.se/2471965.kiana/gallery) #8622700"
![image](https://user-images.githubusercontent.com/80097964/116545459-bfe4ea80-a8f0-11eb-925a-ac1d69aa123d.png)

**Comment by Csardelacal** [comment]
Hey there @KianaOtter. Thanks for letting us know.
Leaving the Phabricator task for reference here: https://phabricator.magic3w.com/T629
