### ISSUE TITLE
All my commission conversations are not loading 

### ISSUE THREAD

**Issue by tetra247** [Csardelacal/YCH-Issues#61]
Platform: desktop & mobile
 Operating system: Android & Windows respectively
 Browser: Chrome
 URL: https://crm.commishes.com/task/show/410131/ https://crm.commishes.com/task/show/394409/ https://crm.commishes.com/task/show/398868/ https://crm.commishes.com/task/show/426192/
 
 What were you trying to do: Look at and respond to the artists posts on the above commissions
 
 What was supposed to happen: The conversation chains are supposed to load correctly 
 
 What happened: the last image that was uploaded to in the conversation is broken and all that is visible after that is a blank white page.

**Comment by drushisan** [comment]
Im having the exact same issue!  I have work to submit and pay for and this is really worrying me.

**Comment by midnight8dragon** [comment]
I'm having the same issue, as well. It's with all of my commissions.

**Comment by terakat** [comment]
I'm having the same issue, the artist responded and it's seen in the preview of the commission, but when I enter the CRM it doesn't show the new update.
