### ISSUE TITLE
SQL Syntax error

### ISSUE THREAD

**Issue by DocMew** [Csardelacal/YCH-Issues#80]
When I try to log into my account, this error crashes:

![photo_2023-03-03_17-22-18](https://user-images.githubusercontent.com/126890980/222749507-ab826b1e-e580-49f6-bbc9-32e60b3042d4.jpg)

And if I refresh the page, this crashes:

![photo_2023-03-03_17-22-47](https://user-images.githubusercontent.com/126890980/222750033-66771a09-189b-4084-bd87-4c2061929b57.jpg)

And until I clear the cookies, I can't get back to the site.

**Comment by Csardelacal** [comment]
Hey there! Thanks for letting me know. I just published https://github.com/Csardelacal/PHPAuthServer/commit/d50f9c095490c0b523bf3b262b272a6b6985a086 which should fix the SQL issue you reported. The fact that the log-in was broken as a conclusion should be going away automatically.

Thanks for letting me know. If anything else crops up, feel free to let me know. :)
