### ISSUE TITLE
Сan't get into the feed section

### ISSUE THREAD

**Issue by DocMew** [Csardelacal/YCH-Issues#85]
![image](https://user-images.githubusercontent.com/126890980/235462736-0a1c038e-e7a4-4501-8226-3572090d79d1.png)

**Comment by Csardelacal** [comment]
Hi doc! We've had a server issue that should be resolved now. Can you check on your end?

**Comment by DocMew** [comment]
Now it works, thank you!

**Comment by Csardelacal** [comment]
Awesome! Thanks for reporting it!
